# 多进程框架

多进程无非就是，想让多核同时执行运算，在使用的时候，如果处处都需要把申请进程池、进程运算、关闭进程写清楚，对使用多进程非常不便，因此希望能做到，在需要执行多进程操作的时候，减少对原逻辑代码的干扰，直接调用多进程框架的函数，即可。本文试图实现这个功能。

要执行多进程，其实就是把一件事情异步的分给很多人去做，所以，需要明确的东西就是：

1. 做什么，函数功能
2. 需要什么资源，资源可能不止一种，包括主资源，和附属资源(其他参数)
3. 输出什么，需要什么结果


> 应该是没有办法一个框架解决所有问题，但是一个相同应该可以用一个或多个框架去实现相同的调用

# 代码实现

In [16]:
import pandas as pd

In [4]:
# 数据匹配
def merge_process(df, df_necessary, func=None, **args):
    from random import randint
    from multiprocessing import Process, Pool, cpu_count
    
    df_result = pd.DataFrame()    
    pool = Pool(cpu_count())
    
    # 将df切割成若干块
    df["grp_no"] = df.apply(randint(1, 100))
    
    print("I am ok")
    for no in range(1, 101):
        df_sub    = df[df["grp_no"] == no]
        df_res    = pool.apply_async(lambda x, y:x.merge(y), args=(df, df_necessary, ))
        df_result = df_result.append(df_res)
        
    pool.close()
    pool.join()
    print("Execution Finished!")
    
    return df_result

In [17]:
df         = pd.read_csv(r"E:\vocation\2.1.数据集\credit_card\credit_card.csv")
df_compare = pd.read_csv(r"E:\vocation\2.1.数据集\credit_card\credit_card.csv")

df.head()

,信用卡顾客编号,申请书来源,瑕疵户,逾期,呆账,借款余额,退票,拒往记录,强制停卡记录,张数,...,个人月收入,个人月开销,住家,家庭月收入,月刷卡额,宗教信仰,人口数,家庭经济,血型,星座
0,CDMS0000001,5,2,2,2,2,2,2,2,1,...,1,1,1,1,1,2,4,4,4,10
1,CDMS0000002,3,2,2,2,2,2,2,2,2,...,1,2,1,1,2,1,4,4,1,5
2,CDMS0000003,2,2,2,2,2,2,2,2,2,...,1,1,1,1,6,6,6,5,1,7
3,CDMS0000004,3,2,2,2,2,2,2,2,2,...,1,1,1,1,4,2,4,3,2,6
4,CDMS0000005,6,2,2,2,2,2,2,2,2,...,1,3,1,1,5,1,4,3,4,6

In [18]:
df.merge(df_compare, on=["信用卡顾客编号"])

,信用卡顾客编号,申请书来源_x,瑕疵户_x,逾期_x,呆账_x,借款余额_x,退票_x,拒往记录_x,强制停卡记录_x,张数_x,...,个人月收入_y,个人月开销_y,住家_y,家庭月收入_y,月刷卡额_y,宗教信仰_y,人口数_y,家庭经济_y,血型_y,星座_y
0,CDMS0000001,5,2,2,2,2,2,2,2,1,...,1,1,1,1,1,2,4,4,4,10
1,CDMS0000002,3,2,2,2,2,2,2,2,2,...,1,2,1,1,2,1,4,4,1,5
2,CDMS0000003,2,2,2,2,2,2,2,2,2,...,1,1,1,1,6,6,6,5,1,7
3,CDMS0000004,3,2,2,2,2,2,2,2,2,...,1,1,1,1,4,2,4,3,2,6
4,CDMS0000005,6,2,2,2,2,2,2,2,2,...,1,3,1,1,5,1,4,3,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,CDMS0065531,4,2,2,2,2,2,2,2,2,...,4,2,5,4,5,7,6,2,4,6
65531,CDMS0065532,3,2,2,2,2,2,2,2,2,...,4,2,5,4,6,3,6,1,4,4
65532,CDMS0065533,3,2,2,2,2,2,2,2,2,...,4,2,5,4,3,1,4,1,3,1
65533,CDMS0065534,6,2,1,1,1,1,1,1,3,...,4,4,5,4,2,6,1,3,1,12
65534,CDMS0065535,5,2,2,2,2,2,2,2,1,...,1,1,1,1,1,2,4,4,4,10

In [20]:
df_res = merge_process(df, df_compare)

AttributeError: 'NoneType' object has no attribute 'head'